platform :ios,'8.0'
target 'Yu' do

pod "Masonry"   ,  '~> 1.1.0'
pod "MJExtension"
pod "SDWebImage"
pod "AFNetworking"
pod "MJRefresh"

pod "ReactiveObjC"
pod 'IQKeyboardManager','~> 5.0.3'
pod "YYText"
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'
pod 'JPush'
end
